name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Docker tags
        id: meta
        run: |
          VERSION=$(grep 'youtube-transcript-api==' requirements.txt | cut -d'=' -f3)
          echo "tags=oldgrandpavanu/youtubetranscriptapi:${VERSION},oldgrandpavanu/youtubetranscriptapi:latest" >> $GITHUB_OUTPUT
          echo "Tagging Docker image with version: ${VERSION}"

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}